name: taskly
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  dashed_circular_progress_bar: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
  - images/

  fonts:
    - family: Winky Rough
      fonts:
        - asset: fonts/WinkyRough-VariableFont_wght.ttf
        - asset: fonts/WinkyRough-Italic-VariableFont_wght.ttf
          style: italic
    
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
    
    - family: Caveat
      fonts:
        - asset: fonts/Caveat-VariableFont_wght.ttf